config/routes.rb
MiniSurvey::Application.routes.draw do
  resources :surveys do
    resources :questions
    resources :answers, 
      :only => [:index, :create] do
        get :data, 
          :on => :collection
    end
    get :watch, 
      :on => :member
  end

  resources :users, 
    :except => [:index]

  resources :sessions, 
    :only => [:new, :create]
  match 'sessions/destroy' => 'sessions#destroy', :as => :destroy_session
  # You can have the root of your site routed with "root"
  root :to => 'sessions#new'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  has_many :surveys,
    :dependent => :destroy
  
  has_many :answers,
    :dependent => :destroy
  
  has_many :watches,
    :dependent => :destroy
  
  has_and_belongs_to_many :surveys_watched,
    :join_table => :watches, :class_name => 'Survey',
    :association_foreign_key => :survey_id, :foreign_key => :user_id
  
  accepts_nested_attributes_for :answers,
    :allow_destroy => true,
    :reject_if => lambda { |answer| answer[:choice].nil? }
  
  accepts_nested_attributes_for :watches,
    :allow_destroy => true,
    :reject_if => lambda { |watch| watch[:survey].nil? }
  
  attr_protected :last_login
  
  mount_uploader :avatar, AvatarUploader
  
  scope :that_answered_survey, lambda { |survey| select("DISTINCT(users.id)").joins(:answers).where('answers.survey_id = ?', survey.is_a?(Survey) ? survey.id : survey) }
  
  validates :password, 
    :length => { :minimum => 3 },
    :unless => Proc.new { |user| user.password.blank? }
    
  validates :password,
    :presence => true,
    :on => :create
  
  validates :password_confirmation,
    :presence => true,
    :unless => Proc.new { |user| user.password.blank? }
  
  validates :name,
    :presence => true
    
  validates :email,
    :presence => true,
    :email => true
  
  validates :email,
    :uniqueness => { :case_sensitive => false },
    :on => :create

  validates_integrity_of  :avatar
  validates_processing_of :avatar
  
  after_create :set_last_login_to_now
  
  def authenticate(*args, &block)
    set_last_login_to_now
    super(*args, &block)
  end
  
  def answered_survey?(survey)
    self.answers.where('answers.survey_id = ?', survey.is_a?(Survey) ? survey.id : survey).count > 0
  end
  
  def answered_choice?(choice)
    self.answers.where('answers.choice_id = ?', choice.is_a?(Choice) ? choice.id : choice).count > 0
  end
  
  def watches?(survey)
    self.watches.where('watches.survey_id = ?', survey.is_a?(Survey) ? survey.id : survey).count > 0
  end
  
  private
  
  def set_last_login_to_now
    self.update_attribute :last_login, Time.now
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  before_filter :authenticate,  :except => [:new, :create]
  before_filter :authorize,     :only => [:edit, :update, :destroy]
  helper_method :authorized?

  def show
    @user = User.find(params[:id])
    respond_with @user
  end

  def new
    @user = User.new
    respond_with @user
  end

  def edit
    @user = User.find(params[:id])
    respond_with @user
  end

  def create
    @user = User.new(params[:user])
    @user.save
    respond_with @user do |format|
      format.html { sign_in(params[:user]); redirect_to root_path, :notice => 'Seja bem-vindo, agora crie uma pesquisa!' } if @user.valid?
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    respond_with @user do |format|
      format.html { redirect_to @user }
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @user do |format|
      format.html { redirect_to :controller => :sessions, :action => :destroy }
    end
  end
  
  private
  
  def authorize
    unless authorized?
      flash[:warning] = 'Você não tem permissão para acessar essa página'
      redirect_to current_user
    end
  end
  
  def authorized?
    @requested_user ||= User.find(params[:id])
    current_user.id == @requested_user.id
  end
end

app/views/users/_form.html.haml
= simple_form_for @user, :html => {:multipart => true} do |f|
  = f.error_notification
  .inputs
    = f.input :name,  :input_html => {:class => :large}
    = f.input :email, :input_html => {:class => :large}, :disabled => !@user.new_record?
    = f.input :password,              :required => @user.new_record?
    = f.input :password_confirmation, :required => @user.new_record?
    .user
      = image_tag @user.avatar_url, :alt => @user.name, :class => 'avatar'
      = f.input :avatar, :as => :file
      = f.input :avatar_cache, :as => :hidden
  .actions
    = f.button :submit

app/views/users/edit.html.haml
- content_for(:title) { "Editar perfil - %s" }
= link_to 'Voltar', current_user, :class => :back
%h1 Editar perfil
= render 'form'

app/views/users/new.html.haml
- content_for(:title) { "Registre-se - %s" }
= link_to 'Voltar', root_path, :class => :back
%h1 Registre-se
= render 'form'

app/views/users/show.html.haml
- content_for(:title) { (authorized? ? "Minha conta" : @user.name) + " - %s" }
= flash_messages
.user
  = image_tag @user.avatar_url, :alt => @user.name, :class => 'avatar'
  - if authorized?
    %ul.actions
      %li= link_to 'Editar perfil', edit_user_path(@user)
      %li= link_to 'Excluir conta', @user, :confirm => 'Tem certeza?', :method => :delete
  %h3= @user.name
  %p
    %em
      = @user.email
    %br
    - unless authorized?
      %small
        Último acesso em
        = @user.last_login.strftime("%d/%m às %H:%M")
    %br
    %br
    %br
    = link_to 'Incluir nova pesquisa', new_survey_path, :class => 'button' if authorized?
%h2
  Minhas pesquisas
%table.surveys
  = render @user.surveys
  - if @user.surveys.empty?
    %tr
      %td.empty
        Você não criou nenhuma pesquisa.
        = link_to 'Crie uma agora', new_survey_path if authorized?
%h2
  Pesquisas favoritas
%table{:class => 'surveys watched'}
  = render @user.surveys_watched
  - if @user.surveys_watched.empty?
    %tr
      %td.empty
        Você não marcou nenhuma pesquisa como favorita.
  