config/routes.rb
MiniSurvey::Application.routes.draw do
  resources :surveys do
    resources :questions
    resources :answers, 
      :only => [:index, :create] do
        get :data, 
          :on => :collection
    end
    get :watch, 
      :on => :member
  end

  resources :users, 
    :except => [:index]

  resources :sessions, 
    :only => [:new, :create]
  match 'sessions/destroy' => 'sessions#destroy', :as => :destroy_session
  # You can have the root of your site routed with "root"
  root :to => 'sessions#new'
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to  :user
  
  delegate :name,
    :to => :user, :prefix => true, :allow_nil => true
  
  has_many    :questions,
    :dependent => :destroy
    
  has_and_belongs_to_many :watches,
    :join_table => :watches, :association_foreign_key => :survey_id, :foreign_key => :user_id
    
  accepts_nested_attributes_for :questions, 
    :allow_destroy => true,
    :reject_if => lambda { |question| question[:title].blank? }
  
  scope :not_private, where('surveys.is_private = ?', false)
  
  validates   :user,
    :presence => true,
    :associated => true
  
  validates   :title,
    :presence => true,
    :length => { :minimum => 3 }
    
  def private?
    self.is_private || false
  end
  
  def total
    User.includes("surveys").that_answered_survey(self).count
  end
end

app/controllers/surveys_controller.rb
# encoding: utf-8
class SurveysController < ApplicationController
  before_filter :authenticate
  
  before_filter :not_allow_duplicated_answers, 
    :only => [:show]
    
  before_filter :authorize, 
    :only => [:edit, :update, :destroy]
    
  before_filter :protect_surveys,
    :only => [:show]
    
  helper_method :authorized?
  
  respond_to :js, 
    :only => :watch
    
  delegate :name,
    :to => :user, :prefix => true
  
  def index
    @surveys = Survey.not_private.all
    respond_with @surveys
  end

  def show
    @survey = Survey.find(params[:id])
    respond_with @survey
  end

  def new
    @survey = Survey.new
    2.times do
      question = @survey.questions.build 
      3.times { question.choices.build }
    end
    respond_with @survey
  end

  def edit
    @survey = Survey.find(params[:id])
    respond_with @survey
  end

  def create
    @survey = Survey.new(params[:survey])
    @survey.user = current_user
    @survey.save
    respond_with @survey do |format|
      format.html { redirect_to @survey }
    end
  end

  def update
    @survey = Survey.find(params[:id])
    @survey.update_attributes(params[:survey])
    respond_with @survey do |format|
      format.html { redirect_to @survey }
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    respond_with @survey
  end
  
  def watch
    @survey = Survey.find(params[:id])
    if current_user.watches?(@survey)
      current_user.surveys_watched.delete(@survey)
    else
      current_user.update_attributes :watches_attributes => [{:survey => @survey}]
    end
    respond_with @survey do |format|
      format.html { redirect_to current_user }
    end
  end
  
  private
  
  def deny_authorization
    flash[:warning] = 'Você não tem permissão para acessar essa página'
    redirect_to current_user
  end
  
  def authorize
    deny_authorization unless authorized?
  end
  
  def authorized?
    find_survey
    current_user.id == find_survey.user.id
  end
  
  def protect_surveys
    deny_authorization if find_survey.private? and current_user.id != find_survey.user.id
  end
  
  def not_allow_duplicated_answers
    find_survey
    redirect_to survey_answers_path(find_survey) if current_user.answered_survey?(find_survey)
  end
  
  def find_survey
    @requested_survey ||= Survey.find(params[:id])
  end
end

app/views/surveys/_actions.html.haml
- if authorized?
  %ul.actions
    %li= link_to 'Ver respostas', data_survey_answers_path(survey)
    %li= link_to 'Editar', edit_survey_path(survey)
    %li= link_to 'Excluir', survey, :confirm => 'Tem certeza?', :method => :delete

app/views/surveys/_choice_fields.html.haml
.choice
  = radio_button_tag '', '', false, :disabled => true
  = f.input :title, :as => :string, :label => false, :required => false
  = link_to_remove_fields('Remover', f)

app/views/surveys/_form.html.haml
= simple_form_for(@survey) do |f|
  = f.error_notification
  .inputs
    = f.input :title, :input_html => {:class => :very_large}
    = f.input :is_private
    = f.simple_fields_for :questions do |builder|
      = render 'question_fields', :f => builder
    = link_to_add_fields('Adicionar', f, :questions)
  .actions
    = f.button :submit

app/views/surveys/_question_fields.html.haml
.question
  %strong Pergunta
  %a{:href => '#', :'data-nested' => 'remove'} Remover
  = f.input :title, :input_html => { :rows => 2}, :label => false, :required => false
  = f.simple_fields_for :choices do |builder|
    = render 'choice_fields', :f => builder
  = link_to_add_fields('Adicionar', f, :choices)

app/views/surveys/_survey.html.haml
%tr{:class => cycle('even', 'odd') + " survey_#{survey.id}"}
  %td{:width => "10"}
    - if current_user.watches?(survey)
      - star = image_tag "star.png",       :alt => 'Favorita'
    - else
      - star = image_tag "star_empty.png", :alt => 'Favorita'
    = link_to star, watch_survey_path(survey), :class => :watch, :remote => true
  %td
    = link_to survey.title, survey
    - if survey.private?
      = image_tag "lock.png", :alt => 'Pesquisa privada'
  %td{:width => "40%", :align => 'right'}
    %small
      Criada em
      = survey.created_at.strftime('%d/%m/%Y às %H:%M')
      por
      = link_to survey.user_name, survey.user

app/views/surveys/edit.html.haml
- content_for(:title) { "Editar pesquisa - %s" }
= link_to 'Voltar', current_user, :class => :back
%h1 Editar pesquisa
= flash_messages
= render 'form'

app/views/surveys/index.html.haml
- content_for(:title) { "Pesquisas - %s" }

%form{:url => surveys_path, :method => :get, :class => :search}
  %input{:type => :text, :name => :q, :value => params[:q]}
  %input{:type => :submit, :value => 'Procurar'}

%h1 Pesquisas

%table.surveys
  = render @surveys
  - if @surveys.empty?
    %tr
      %td.empty
        Nenhuma pesquisa disponível.

app/views/surveys/new.html.haml
- content_for(:title) { "Incluir pesquisa - %s" }
= link_to 'Voltar', current_user, :class => :back
%h1 Incluir pesquisa
= render 'form'

app/views/surveys/show.html.haml
- content_for(:title) { "Pesquisa: #{@survey.title} - %s" }
= link_to 'Voltar', surveys_path, :class => :back
%h1 
  Pesquisa
= render 'actions', :survey => @survey
.survey
  %h3
    = @survey.title
  = flash_messages
  = simple_form_for :answers, :url => survey_answers_path(@survey) do |f|
    %ol
      - @survey.questions.each do |question|
        %li
          %strong= question.title
          %ul
            = f.collection_radio "question_#{question.id}", question.choices.map { |choice| [choice.id, choice.title] }, :first, :last
    .actions
      = f.button :submit, 'Enviar respostas'

app/views/surveys/watch.js.erb
<% partial = render "survey", :survey => @survey %>
$('tr.survey_<%= @survey.id %>').replaceWith("<%= escape_javascript(partial) %>");
<% if current_user.watches?(@survey) %>
  $('table.watched').append($("<%= escape_javascript(partial) %>"));
  $('table.watched td.empty').parent().remove();
  // Set style
  $('table.watched tr').removeClass('odd even');
  $('table.watched tr:odd').addClass('odd');
  $('table.watched tr:even').addClass('even');
<% else %>
  $('table.watched tr.survey_<%= @survey.id %>').remove();
<% end %>