config/routes.rb
MiniSurvey::Application.routes.draw do
  resources :surveys do
    resources :questions
    resources :answers, 
      :only => [:index, :create] do
        get :data, 
          :on => :collection
    end
    get :watch, 
      :on => :member
  end

  resources :users, 
    :except => [:index]

  resources :sessions, 
    :only => [:new, :create]
  match 'sessions/destroy' => 'sessions#destroy', :as => :destroy_session
  # You can have the root of your site routed with "root"
  root :to => 'sessions#new'
end

app/views/layouts/_error_messages.html.haml
- if record.errors.any?
  #error_explanation
    %h2= "#{pluralize(record.errors.count, "erro")} impediram este registro de ser salvo:"
    %ul
      - record.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/application.html.haml
!!! 5
%html{:lang => 'pt'}
  %head
    %meta{:charset => 'utf-8'}
    - title = "%s" 
    - title = yield :title if content_for? :title
    %title= title % "Mini Survey" 
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tag
  %body
    #master
      %h6 
        Mini Survey
        %sup
          app
      - if authenticated?
        %ul#navigation
          %li{:class => (controller_is?(:users) and params[:id].to_i == current_user.id ? 'selected' : nil)}
            = link_to "Minha conta", user_url(current_user)
          %li{:class => controller_is?(:surveys, :answers) ? 'selected' : nil}
            = link_to "Pesquisas", surveys_url
          %li{:class => 'exit'}
            = "Olá #{current_user.name},"
            = link_to "Sair", destroy_session_url
      #content
        = yield